<?php

define("PART", 2);

function flood_fill(&$data, $posX, $posY, $mapWidth, $mapHeight, $plant, $fieldMarker)
{
    if ($posX < 0 || $posX >= $mapWidth ||
        $posY < 0 || $posY >= $mapHeight || 
        $data[$posY][$posX] != $plant) 
    {
        return;
    }
    
    $data[$posY][$posX] = $fieldMarker;
    
    flood_fill($data, $posX+1, $posY, $mapWidth, $mapHeight, $plant, $fieldMarker);
    flood_fill($data, $posX-1, $posY, $mapWidth, $mapHeight, $plant, $fieldMarker);
    flood_fill($data, $posX, $posY+1, $mapWidth, $mapHeight, $plant, $fieldMarker);
    flood_fill($data, $posX, $posY-1, $mapWidth, $mapHeight, $plant, $fieldMarker);
}

function measurePlantFields(&$data, $mapWidth, $mapHeight, $fieldMarker, &$area, &$perimeter) {
    $area = 0;
    $perimeter = 0;
    
    if (PART == 1)
    {
        $width = $mapWidth;
        $height = $mapHeight;
    } 
    else 
    {
        $width = $mapWidth+1;
        $height = $mapHeight+1;
    };
    
    for ($y = 0; $y < $height; $y++) {
        for ($x = 0; $x < $width; $x++) {
            if (PART == 1) 
            {
                if ($data[$y][$x] == $fieldMarker) {
                    $area += 1;
                    if ($x <= 0 || $data[$y][$x-1] != $fieldMarker)            $perimeter += 1;
                    if ($x >= $mapWidth-1 || $data[$y][$x+1] != $fieldMarker)  $perimeter += 1;
                    if ($y <= 0 || $data[$y-1][$x] != $fieldMarker)            $perimeter += 1;
                    if ($y >= $mapHeight-1 || $data[$y+1][$x] != $fieldMarker) $perimeter += 1;
                }
            }
            else
            {
                    $vertex_lut = array(0,1,1,0,1,0,2,1,1,2,0,1,0,1,1,0);
                    $kernel = 0;
                    if ($y < $mapHeight && $x < $mapWidth) {
                        $kernel = ($data[$y][$x] == $fieldMarker); 
                        $area += $kernel;
                    }
                        
                    if ($y < $mapHeight && $x > 0) {
                        $kernel = $kernel | ($data[$y][$x-1] == $fieldMarker) << 1;
                    }
                    
                    if ($y > 0 && $x < $mapWidth) {
                        $kernel = $kernel | ($data[$y-1][$x] == $fieldMarker) << 2;
                    }
                    
                    if ($y > 0 && $x > 0) {
                        $kernel = $kernel | ($data[$y-1][$x-1] == $fieldMarker) << 3;
                    }
                    
                    $perimeter += $vertex_lut[$kernel];
            }
        }
    }
}

function run($data) {
    $plants = [];
    
    $width = strlen($data[0]);
    $height = count($data);
    
    for ($y = 0; $y < $height; $y++) {
        $line = array_unique(str_split($data[$y]));
        foreach ($line as $plant) {
            if (!in_array($plant, $plants, true)) {
              array_push($plants, $plant);
            }
        }
    }
    
    $result = 0;
    $area = 0; 
    $perimeter = 0;
    
    foreach ($plants as $plant) {
        $flood_map = $data;
        $fieldIndex = 0;
        
        for ($y = 0; $y < $height; $y++) {
            for ($x = 0; $x < $width; $x++) {
                if ($flood_map[$y][$x] == $plant) 
                {
                    $fieldMarker = chr($fieldIndex + 32);
                    flood_fill($flood_map, $x, $y, $width, $height, $plant, $fieldMarker);
                    measurePlantFields($flood_map, $width, $height, $fieldMarker, $area, $perimeter);
                    $result = $result + ($area * $perimeter);
                    $fieldIndex += 1;
                }
            }
        }
    }
    
    print($result);
}

$data = array(
    "RRRRIICCFF",
    "RRRRIICCCF",
    "VVRRRCCFFF",
    "VVRCCCJFFF",
    "VVVVCJJCFE",
    "VVIVCCJJEE",
    "VVIIICJJEE",
    "MIIIIIJJEE",
    "MIIISIJEEE",
    "MMMISSJEEE"
);

$data1 = array(
    "FFFFVVVVCCCUUUUUUUUUUUUUUTUFFFFEEEEEEEXXBBBBBBBBBBBBBBEEEEEEEEEEEEECCCCCCCCCCCCCCCQQUUUZZZZZZZZZUZZZQUUUUUUIIIIIIIIDQQQQQQQQQNNNNNNNNNNNNNNN",
    "FFFVVVVVVVVUUUUUUUUUUUUUUUUFFFFEEEEEEEXXXBBBBBBBBEEEEEEEEEEEEEEEECCCCCCCCCCCCCCCCCQQUUZZZZZZZZZZZZZZUUUUUUUIIFFFOIDDDDQQQQQQNNNNNNNNNNNNNNNN",
    "FFFVVVVVVVVUUXUUUUUUUUUUUUUFXEEEEEEEEEXXXBBBBBBBBEEEEEEEEEEEEEEEECCCCCCCCCCCCCCCCQQQZZZZZZZZZZZZZZZZAUUUUUUOIFFFOIIDDDQQQQQQQQNNNNNNNNNNNNNN",
    "FFFVVVVVVFFFUXUUUUUUUXUUXQXXXXXEEEEEEXXFFBBBBBBBBBBEEEEEEEEEEEEEEECCCCCCCCCCCQQCCQQQZZZZZZZZZZZZZZGZAAUUUUOOOOOOODDDDDDDDDDQQQQNNNNNNNNNNNNN",
    "FVVVVVVVVVVFUUUUUUUXXXXXXXXXXRRXEEECEXXBBBBBBBBBBBBHEEEEEEEEEEEEECCCCCCCCCCCCCQQQQQQZZZCZZZZDDZGZZGAAAUUUUOOOOOOOOOFFDDDDDDDDQDNNNNNNNNNNNNN",
    "FVVVVVVVVVVFUUFFUUUUXXXXXXXXXXXXEEVEEXXBBBBBBBBBBBHHHEEEEEEEEEEEECCCCCOCCCCQQQQQQQQQQZZZZZZZZZGGGZGAAAAUUUDDOOOOOOOODDDDDDDDDDDBBBNNNNNNNNNN",
    "FFFVVVVVVVVFFUFFUUUUXXXXXXXXXXXXXEEEEXXBBBBBBBBBBBHHHHHEZZEEWWWEECECCCOOCCCCQQQQQQQQQQQZQZZZZZGGGGGAAAAUUUUOOOOOOOOODDDDDDDDDDBBBBNNNNNFFFNN",
    "FFFFFFVVZVVFFFFFUUUUUUUXXXXXXXXXXXEXXXXXXBBBBBBBHHHHHFFJZZEWWWWWEEECCCOOCOOQQQQQQQQQQQQQQQZZZZGGGAAAAAKKKUKOOOOOOOOOODDDDDDDDBBBBBNNNFFWFFFF",
    "CCCCFFFVVVVVFFAFUUUUUQXXXXXXXXXXXXEXXXXXXXBBBBBBBHHHHFCJJJWWEWWWWECCOOOOOOOQQQQQQQQQQQQQQQQQQZGGKAAAAKKKKKKOOOOOOOOOOOODDDDDBBBBBBBNNFFFFFFF",
    "CCCRCCFVVFFFFFAFAUUZZQQXXXXXXXXXXXEENXXXXXXXBYYYYYYYFFCJJJJWWWWWWWWCOOOOOOOUUQQQQQQQQQQQQQQQQQQKKKKKKKKKKKKOOOOOOOOOOODDDDDDBBBBBBBNBFFFFFFF",
    "CCCCCCFFFFFFAAAAAAZZZZXXXXXXXXEEEEEENNVVXXXNNYYYYYYYFFCCJJJWWWWWWWWOOOOOOOOUQQQQQQQQXXXQQQQQQQQPKKKKKKKKKKKOLOOOOOOOOODDDDDDDDBBBBBBBFFFFFFF",
    "CCCCCCCFFFAAAAAAAZZZZZXXXXXXXXXEEEEVNNVVQQQNNYYYYYYYFFCCCWWWWWWWWWWJOOOOOOOOOQQQQQXXXXMQQQQQLQBPPKKKKKKKKKKKOOOOOOOODDDDDDDDDDDBBBBEBFFFFFFF",
    "CCCCCHBBBFFFAAAAAAZZZXXXXXXXXXXEEEEVVVVVQNNNNYYYYYYYFFFCWWWWWWWWWWOOOOOOOOOOOOQQQQQXXXXQQQQEPPBPPPKKKKKKKKKOOOOOOJOOXDDDDDDDDDBBBBBBBBBFFFFF",
    "BCBCCBBBBFFFAAAAAAAZZXZSXXXNXXEEEVEVAVVVNNNNNYYYYYYYFFFFFNNWFWWWWWPOOOOOOOOOOOZQQQZXXXXXPQLPPPBPPKKKKKKKKKKKKOOOOJJJXXDDDDDDDDGBBBBBBBBFFFFF",
    "BBBBBBBBZZZZAAAABBBZZZZZZYNNNEEEVVVVVVVVVVYYYYYYYYYYFFFFNNWWWWWURWPOOOOOOOOAOOZQQQZXXXXXPPPPPPPPPUPKKKKKKKKKKPOJJJJJJXXDDDDDDDBBBBBBBBFFFFFF",
    "BBBBBBBZZZZZZAABBBBZZZZZZNNNNEVVVVVVVVVVVVYYYYYYYYYYFFFFNNWNWWYUUAOOOOOOOOOOOJJJQHXXXXXXPPPPPPPPPPPPKKKKKKPPPPPDJJJXXXDDDDDDDGBBBBBBFFFFFFFF",
    "BBBBBBBZZZZZZAAAZBBBZZBBBBNNNVVVVVVVVVVVVVYYYYYYYYYYMFNNNNNNWWUUUUOOOOOOOOOOOJJJHHXXXXXPPPPPPPPPPPPPKKKKPPPPPPPDJJJJXXXXDDDDDXXXBFFFFFFFFFFF",
    "BBBBBBBFFFZZZZZZZBBBZBBBBBNNNNVVVVVVVVVVVVYYYYYYYYYYANNNNUUNUUUUUUOOOOOOOOOOJJJJJHXXXXXZPPPPPPPPPPPPPKJPYPPPPPPPJJXXXXXXDXDDXXXXKUUFFFFFFFFF",
    "BBBBBBFFZFZZZZZZZBBBBBBBBNNNNNVVVVVVVVVVVVYYYYYYYYYYANNNUUUUUUUUUUOOOOOOOOOOJJJJJXXXXXXZPPPPPPPPPPPPPKJPPPPPPPPPJJXXXXXXXXXDXXXXXUUFFFFFFFFF",
    "BBBBBFFZZZZZZZZZZBBBBBBBBNNNNNNNVVVVVVVVVYYYYYYYYYYAANNNNNUUUUUUUOOCOOOOOJJJJJJJJXXXXXXXCPPPPPPPPPPPPKJJPJPPPPPPXJXXXXXXXXXXXXXXXUUUUFFFFFFF",
    "BBBBBFFZZZZZZZZZZBBBBBBBBNNNNNNNNVVVVPVVVYYYYYYYYYYYYYYNNNUUUUUUUCCCUUUUOJJJJJJJJJXXXXXXXPPPPPPPPPPPPJJJJJPPPPXXXXXXXXXXXXXVXXXXUUUUUUUUUFFF",
    "BBBBFFFZZZZZZZZZBBBBBBDDDNNNNNNNNNVVVVVVVYYYYYYYYYYYYYYNNIUUUUUUCCCCUUUUOOOOOJJJJJXXXXXXXPPPPPPPPPPPPJDDDPPPPCXXXXCXXXXXXXVVVVUUUUUUUUUUUUFF",
    "VBBBBBFFZZZZZZZZZZBFFBDDDDDNNNNNNNVVVVVVVYYYYYYYYYYYYYYANIIUUUUUUUUUUIIIOOOOOJJJJXXXJKXXQPPPPPPPPPPPJJDYDDPPPPPDDCCCXXXXXXVVVVSUUUUUUUUUUUFF",
    "VBBBBFFFZZZZZZZZZZBFFBBBDDDDNNNNNNNNNNNVWYYYYYYYYYYYYYYANIIIIIUUUUUUUUIIOOOOOJJJJJJJJJUXQQPPPPPPPPEEDJDDDDPPDPPDNCCCXXXXXVVVVGUUUUUUUUUUUUFF",
    "BBBBFFFFFZZZZZZZZZZFFFFBDDDDNNNNNNNNNNNNXYYYYYYYYYYYYYYANIIIIIIUUUUUUIIIOOOOOIJJJJJHJUUUPPPPPURRPAAADDDDPPPDDDDDDCCCCXXXXVVVVUUUUUUUUEUGGGFF",
    "BBBFFFFFFZFZZZZZFZFFFFFBDDDNNNNNNNNNNNNNXXYYYYYYYYYYYYYAAIIIIIIIUUUUUIIIOOOOOIJJJJJUUUUUUUPNPUURRAAADDDDDDDDDDDDFCCCCXXXXXPPPPUUUUUUUGGGGGGG",
    "FFFFFFFFFFFZZZZZFZFFFFDDDDDNNNTNNNNNNXXKXXYYYYYYYYYYYYYAIIIIIIIIUUIUUIIIOOOOOIIIJJJUUUUUUUUUPUURRAAAADDDDDDDDDDDCCCCCCXXXXPPPPGBBUUUUGGGGGGG",
    "FFFFFFFFFFFFFZZZFFFFFFDDDDDNTTTNNNNCCXXXXXXXXMYYYYYYYYYCCIIIIIIIIIIIUIIIIIIIIIIIJTUUUUUUUUUUUUUAAAAAYYDDDDDDDDDDDDCCCEXXYXEPPGGBBUUUUGGGGGGG",
    "FFFFFFFFFFFFFFZFFFFFFFFDTWTTTTTTNNNCCXXXXXXXXXYYYYYYYYYCCIIIQQIIIIIIUUUIIIIHHHHHHIBBUUUUUUUUUUAAAAAADDDDDDDDYEEEEECCCEXBEEEPPPGGGGGGGGGGGGGG",
    "FFFFFFFFFFFFFFZFFFFFFFTLTTTTTTTTNNLXXXXXXXXXXXYYYYYYYYYIIIIIIIJIIICUUHHHHIIHHHHHHIIBUUUUUUUUUUAAAAAAAAAADDDDYEEEEEEEEEEEEEEEEPGGGGGGGGGGGGGG",
    "FPFFFFFFVVFFFFFFFFFTTTTTTTTTTTTNNNXXXXXXXXXXXXXXSSSSCCWWWIIIIWWWWIIKIHHHHHHHHHHHHLLUUUUUUUUIIAAAAAAAAAADDDDDYEEEEEEEEEEEEEEEPPGGGGGGGGGGGGGG",
    "PPPFFFFFVFFFFFFFFFTTTTTTTTTTTTTNNNNXXXXXXXXXXXXXUUUSCUUWWWWWWWWWWIIKKHHHHHHHHHHHHRRMMUUUYUUIIIAAAAAAAAAAAAAAYYEEEEEEGEEEEEEXGGGGGGGGGGGGGGGG",
    "PPPFFFFFFFFFFFFFFFTTTTTTTTTTTTTTNNNXXXXXXXXXKKKKUUUUUUUUWWWWWWWWWWTTTHHHHHHHHHHHHRRRRRUUURUUUIAAAVAAAAAAAAAYYEEEEEEEGGEERRRRCCGGGGGGGGGGGGGG",
    "PPPPPPPFVVFFFFFFFFFFYTTZTTTTTTGTNNXXXXXXXXXXKKKUUUUUUUUUUWWWWWWWHHHHHHHHHHHHHHHHHRRRRRRRRRERIIIAZVAAAAAAAAAYYEEEEEEEGGGRRRRRCEEEEGGGGGGGGGGG",
    "PPPPPPPFVVFFFFFFFFFFTTTTTTTTTTGGGGXXXXXXXXXKUUKUUUUUUUUUUUUWWWWWHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRVVVAAAAAAYYEEEEEEEGGGGRRRRRCEEEEEGGGGGGGGGX",
    "PPPPPPPFVVFFFFFFFFFFAATTTTTTTAGGGGGEXXXXXXKKKUUUUUUUUUUUUUUUWWWWHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRVAAAAAAAAAAJJEEEEEEGGGRRRRRRTEEEEEELLLGGGXX",
    "PPPPPPPPPVVVFFFFFFFFATTTTTTTTTGGGGGEEXXXXXKKKUUUUUUUUUUUUUUWWWIIHHHHHHHHHHHHKKKKKRRRRRRRRRRRRRRRRAAAAAAAAAAJJEEEEEEEGGGRRRRRRTEEEEEIQLXXGGXX",
    "PPPPPPPPPVVFFFFFFFFFFLLTTSSGGGGGGGGGEXXXKKKKKKKUUUUUUUUUUUUWWWIIHHHHHHHHHHHHKKKKKKKRRRRRRRRRRRRRRABAAAAAAAJJJEEEEERRGGGRRRRRRRRQQQQQQLXXXXXX",
    "PPPPPPPPPPPFFOFFFJJFLLLTTGGGGGGGGGGEEEEEEEKEEEEUUUUUUUUUUUUWWWIIHHHHHHHHHHHHKLLLKKKKMMMRRRRRRRRRRRRTAAAAGAJGJGGERRRRGRRRRRRRRQQQQQQQQLLXXXXX",
    "PPSPPPPWAPPOOOFJJJLLLLLGGGGGGGGGGGGGEEEEEEEEEEEEUUUUUUUUUUUWWWWIHHHHHHHHHSSKSLLLLKKMMMMMRRRRRRRRFRTTTAAAGGGGGGGERRRRRRRRRRRRRRRQQQQQQQXXXXXX",
    "PPSSSPPWWPOOOOOOOOOLLLLLLLGGGGGGGGGEEEEEEEEEEEEEUUUUUUUOUUUWQWUIHHHHHHHHHSSSSLLLKKKMMMMMMRRMMRRRRRTTTTTTTGGGGGGGGRRRRRRRRRRRRQQQQQQQQQXXXXXX",
    "SSSWWWWWVPOOOOOOOOOLLLLLLLGEEEGGGGGEEEEEEEEEEEEEEUUUUUUOJJJJUUUUHHHHHHHHHSSSSSLLLLLMMMMMMMMMMMRJTTTJJTTTTTTGGGGGGGRRRRRRRRRRRQQQQQQQQWXXXXXX",
    "SWWWWWWWWCOOOOOOOOOLLLLLLLLEEGGGGGEEEEEEEEEEEEEEEUUUUUOOOJJJUUUUHHHHHHHHHHHHSSLLLLLMMMMMMMMMHHJJJJJJJJJJTTGGGGGGGGRRRYRRRRRRRQQQQQQQQXXXXXXX",
    "SSWWWWWWWWOOOOOOOOOLLLLLLLLELEGGGGEEEEELEEEEHEEHSSOUOUOOOOJJJUUUUSSHHHHHHHHHSSSSSSGGGMMMMMHHHCCJJJJJJJJTTTGGGGGGGGRRYYYRRQQQQQQQQQQQQQSSSXXX",
    "OWWOOWWWOOOOOOOOOOLLLLLLLLLLLEEEEEEELLLLEEEEHHHHHHOOOOOOOOJJUUUUUUUHHHHHHHHHSSSSSSSGMMMMHHHHHAJJJJJJJJJJTTGGGGGGGGRPYYRRRQRQRRQQQQQQQQQSSXBX",
    "OOOOOOOOOOOOOOOOOOOLLLLLLLLLLEEEEEEELLLLEEEEHHHMMMMOOOOOOOOJJUUUUUUUHHHHHHHHSSSSSAGGHHHHHHHHHAAJJJJJJJJJJTTGGGGGYGYYYYYRRRRRRQQQQQQQQIBSBBBB",
    "OOOOOOOOOOOOOOOOOOOLLLLLFFFLLEEEEELLLLLLHEEHHHHMMMMOOOOOOOOJJUUUUUUUHHHHHHHHSSSSAAGGGHHHHHHHHHAJJJJJJJJTTTTGGGGGYYYYYYYYRRRRRRRZZZZZBIBBBBBB",
    "OOOOOOOOOOOOOOOOROOLLLLLLLFVFEEEELLLLLLLHHHHHHHHMMOOOOOOOOOJJPPPPSSSHHHHHHHHSSSAAAGGHHHHHHHHHAAJJJJJJJJTTTTTTGTTTTYYYYYYYRRRRRRRZZZBBBBBBBBB",
    "OOOOOHHHHOOOOOORRRRLLLLLLFFFFEEEELLLLLLHHHHHHHHHHMMMOOOOOOJJJPPPPJSSHHHHHHHHSSAAAAAGHHHHHHHHAAAJJJJJJJTTTTTTTTTTTTYYYYYYYRRRRRRRBZZBBBBBBBBB",
    "OOOOHHHHHOOOOORRRRRRRLLLLYFFFFLLLLLLLLLHHHHHHHHHHMMOOOOOOJJJJPJPJJSSHHHHHHHHSAAAAAAAHAHHHHHHAAAAJJJJTTTTTTTTTTTYYYYYYYYYYRRRRRRRBBBBBBBBBBBB",
    "OOOOHHHHOOOOOOORRRRLLLLLYYFFFFFLLLLLLFFHHHHHHHHHHHOOOOOOOJJJJJJJJJJJHHHHHHHHSSAVAAAAAAAAHHHHHAAAJJJTTTTTTTTTTYYYYYYYYYYYYYRRRRRRDDFBBBBBBBBB",
    "OOOOOOHOOOOOOORRRRRLLHLLYYFFFFFFLLLLFFFFFHHHHHHHHHJJOOOOOJJJJJJJJJJJJPPSSPPPSVAVVAAAUAUAHHHHAAAAAJJAATTAAAAATYYYYYYYYYYYYYVRRZZZDDDBUBBBBBBB",
    "OOOOOOOOOOOOOOOORRRLLHHHHFFFFFFFFLFFFFFFFHHHHHHHHJJJJOOOJJJJJJVJJJJJJPPPPPPPVVVVVVUUUAUAAAAAAAAAAAAAATAAAAAAAOYYYYYYYYYYTYVRZZZZDDDBBBBBBBBB",
    "OOOOOOOOKKOOOORRRRRRLHHHHFFFFFFFFFFFFFFFFHHHHHHHHJJJJJOJJJJVVVVVJOOJPPMPPPPVVVVVEUUUUUUUAAAAAAAAAAAAAAAAAAAAAUUUUYYYYYYYYYYYZZZZZZZZBBBBBBBJ",
    "OOOOUUOOKKOOOOKRRRRBHHHHHFFFFFFFFFFFFFFFHHHHHHHHHHSSJJJJJPPPPPPQOOOJPPPPPPPYYVVVUUUUUUUUAAAAAAAAAAAAAAAAAAAAAAUUYYYYYYYYYYYZZZZZZCCZZBBBBBBJ",
    "OOOUUUUKKKKKKKKRRRRHHHHVHHRFFFFFFFFFCFHHHHHHHHHHHHSSSJJJPPPPPPQQQOOOPPPPPPPPPOVKUUUUUUUUUUAAAAAAAAAAAAAAAAAAAUUUYYYYYYYYYYLEEEZZCCCCCCBBOBVJ",
    "POOUUUUKKKKKKKGGRRSSHHVVVRRRFFFFFFFCCCCCHHHCHHHHHHRSSJJJPPPFPPQQVOOOOOPPPPOPOOUUUUUUUUUUUAAAAAAAAAAAAAAAAAAAAAUUYYYYYYYYYLLEEELZCCCCCCXBOVVJ",
    "POUUUUUKKKKKKKSSRRRSHHRRRRRRRRFFFFCCCCCCCHHCHHHHHHSSSSSPPPPPPPPQVOKKKOOOOOOOOOUUUUUUUUUUAAAAAAAAAAAAAAAAAAAAAUUUYYYYYYYYYRRRRRRRRRRCCCCCOVVJ",
    "POUUUUUUKKJJYYYSRSSSHRRRRRRRRRRCFCCICCCCCCCCHHHHEEEEEEEPPPPPPPPQVVVKKKOOOOOOOOOUUUUUUUUUAAAAAAAAAAAAAAAAAAAAAAUUUYYYYYYYYRRRRRRRRRRCCCCCCVVV",
    "PPUUUUUUJJJJJJSSSSSBBIRRRRRRRRRCFCCCCCCCCCCCCCEEEEEEEEEPPPPPPPPQVVVKKOOOOOOOOOTPPUUUUUAAAAAAAAAAAAAAAAAAAAAAUUUUUUYYUUYYYRRRRRRRRRRCCCCCVVVD",
    "UUUUUUJUJJJJHJSSSSSBBRRRRRRRRRRCCCCCCCCCCCCCCCEEEEEEEEEPPPPPPPPQVVHKKKOOOOOOOOTPPPUUUUAUAAAAAAAAAEAAAAANGAAAUUUUUUUYUULYLRRRRRRRRRRVVVVVVVVD",
    "JUUUJJJJJJJJJESSSBBBBRRRRRRRRRRCPCCCCCCCCCCCCCEEEEEEEEEPPPPPPPPPPPKKKKKOOOOOOTTPPUUUUUUUUUAAAAAAAEEEAANNNNNUUUUUUUUUUULLLRRRRRRRRRRVVVVVVVVD",
    "JJUJJJJJJJJJJSSSSVBBBRRRRRRRRRRRPCRCCCCCGCCCCCEEEEEESPPPPPPPPPPPPPKKKKKKKOOOOTTPPPUUUUUUUUAAEEEEEEEEANNNNNNUUUUUUUUUUUUULRRRRRRRRRRVVVVVVVVV",
    "JJJJJJJJJJJJUUUBBBBBBCCCCRRRRRRRKRRRRRRRCCCCCCEEEEEESPPPPGPPPPGPKKKKKKKJKTTTTTTTTUUUUUHUUUUUUEEEEEEENNNUUUUUUUUUUUUUUULULRRRRRRRRRRVVVVVVVVV",
    "JJJJJJJZZZJUUUUUUCBBCCCCCCCRRRUKKKKRRRRCCCCCCCEEEEEEGGGPGGPGGPGGKKKKKKKKKTTTTTTTTTUUHHHHUUUUUEEEEEEENNNNNNNUUUUUUUUURRRRRRRRRRRRRRRVVVVVVVVV",
    "JJJJJJZZZZZUZUCCCCBBCCCCCCCCGGKKKKRRRRRCCCCCCCEEEEEEGGGGGGGGGGGGKKKKKTTTTTTTTTTTTTTUHHHHHHHHULEEEEEEGNUGGNNNNUUUUUUURRRRRRRLLLUUUUSVVVVVVVVV",
    "JJJZJJZZZZZZZUZJCCCCCCCCCCCCCCOKKKRRRRRRCCCCCCEEEEEEGGGGGGGGGGGGGKKKKKITTTTTTTTTTTUUHHHHUUUUULEEEEEGGCGGNNNNUUZZUUUJRRRRRRRUUUUUUUUUVVVVVVVV",
    "JJJZZZZZZZZZZZZJCCCCCCCCCCCCOOOKKKRRRRCCCCCCCCEEEEEEGGGGGGGGGGGGGGGGIIITTTTTTTTTTTTHHHUHHUUUUUEEEEEGGGGGGGGGGGGZZZUJRRRRRRRUUUUUUUUUUUUUUVVV",
    "JZZZZZZZZZZZZZZZZCCCCCCCCCCOOKKKKKRRRCCCCCCCCCCCCPGGGGGGGGGGGGGGGGIIIZZZATTTTTTTTTHHHHUUUUUUUUAAAEEGGGGGGGGGGGGGGGLLRRRRRRRUPUUUUUUUUUUUUUVV",
    "JZZZZZZZZZZZZZZZCCCRRCRRCCCCOORKRKRRRRCCCCCCCCCCCGGGGGGGGGGGGGGGGGGIIZZZAZTTTTTTTTTHHUUUUUUUUUUAUGGGGGGGGGGGGGGGGGGLLLLLLLLLLPPUUUUUUUUUUUVV",
    "JZZZZZZZZZZZZZZOOCCRRRRRCCCCVORRRRRRRRRRCCCCCCCCCCGGGGGGGGGGGGGGIGIIIZZZZZTTTTTTTTTHHHUUUUUUUUUUUGGGGGGGGGGGUGGGGGGLGLLLLLLLUUUUUUUUUUUUUUVV",
    "JJZZZZZZZZZZZZZOOOCRRRRRRCCRVVVRRRRRRRRCCLLCCCCCCGGUUUUGGGGGGGGGIGIIIZZZZTTTTTTTTTTHHHUUUUUUUUUUUGGGGGGGGGGGGMMGMMGGGLLLLLLLAUUUUUUUUUUUUUVV",
    "JJZZZZZZZZZZZZZORRRRRRRRRRCRVVVRRRRVVRDLLLDDFCCCCUUUUUUUGGGGGGGGIIIIIZZZZTTTTTTTTTHHWWXWWWUUUUUDUDGGGGGGGGGGMFMMMMGGGGLLLLLAAAAUUUUUUUUUUVVV",
    "JJZZZZZZZZZZZZZQQERRRRRRRRRRVVVVVVVVDDDDDDDDFFFYUUUYUUUUGGGGSSGIIIIIIIZIJTTTTTTTTTTHWWWWWWUUUUUDDDDGGGGGGGGGMMMMMMMMGGLLLLLAAAAUUUUUUUVUUUVV",
    "JJJJZZZZZZZZZZQQRRRRRRRRRRRRRVVVVVVVVDDDDDDFFFFYYUYYYUGGGIIGSEGEEIIIIIIIJJJTTTTTTWHHWWWWWWWWWUDDDDDGGGGGGGGGPMMMMMXMMMLLLLAAAAAAUUUUUUVVVVVV",
    "JJJJJZZZZZZZZZQQRRRRRRRRRRRRRVRRRVVVDDDDDDDDFYYYYYYYYYXXGGGGEEEEEIIIIIIJJJJJJTTTTWWWWWWWWWWWWDDGDGDGGGGYGGGGPMMMMMMMMALLAAAAAAAAUUUUVVVVVVVV",
    "JJJJZZZZZZVQZQQRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDYYYYYYYYYXXXXXEEEEEEIIEIIIJJJJJJTTTWWWWWWWWWWKKWDDGGGGGGGGVVGGGMMTMMMAMAAALAAAVAAAVXXUUUVVVVVVV",
    "JJJJZZZZZQQQQQQRRRRRRRRRRRRRRXXRRRRRDDDDDDDDDYYYYYYYYYYXXXXXXEEEEEEEIIJJJJJJJJTTJJWWWWWWWMMMWDGGGGGGGGXVVGGGBMTMMMAAAALLAAAVVAVVXUUUVVVVVJVV",
    "JJJJZZZULQQQQQQRRRRRRRRRRRRRRRRRRRRDDDDDDDDDDYYYYYYYYYYYXXXXXXEEEEEEJIJJJJJJJJJOXXWWWWWWWMMMDDGGGGGGGGVVVGVVMMMMMMAAAAAAAAVVVVVXXXXXVVVVJJVV",
    "JJJUUZZULLQQQQQRRRRRRRRRRRRRRRRRRRRRRRDDDDDGYYYYYYYYYYYYXZZXXXEEEEEEJJJJJJJJJJJXXXZWWWFFFMCMDDDDGGGGGGVVVVVMMMMMMMMAAAAAAAVVVVVXXVXVVVVJJJVV",
    "JJJUUUUUUQQQQQQRRRRRRRRRRRRRRRRRRRRRRRRDDDDDRYYYYYYYYYZYXZZXXXEEEEEEJJJJJJJJJJJXXXXFFFFFFDDMDDDDDGGGGGVVVVVAMMMMAAAAAAAVAVVVVVVVXVVVVVJJJJJV",
    "JUUUUUUUUUQQQQQRRRRRRRRRRRRRRRRRRRRRRRRRDDDHRYYYYYYYYYZXXXZZXXEEEEEEJJJJJJJJJJJJXXXXXXXXDDDDDDDDDGGGGGGVVVVAAAMAAADAAAAVVVVVVVVYVVVVRJJJJJJV",
    "JUUUUUUUUUQCQQQQRRRRNNRNRRRRRRRRRRRRRRRRRRRRRRYYYYYYYYZZXZCZZEEEEEEEEEJJJJJJJJJJXXXXXXDDDDDDDDDGGGGGGGGGVAAAAAAAADDDDDDVVKVVVVVYVQQJJJJJJJJJ",
    "JJUUUUUUUUCCCCCVRRRRNNNNNRRRRRRRRRRRRRRRRRRRRRRYYYYYZZZZZZZZZZZEEEEEEEEJJJJJJJJJJXXXXXDDDDDDDDDGGGGGGGGAAAAAAAAAADDDDDDVVVVVVVYYVQQJVJJJJJJJ",
    "JVUUUUUUUCCCCCCVVVNNNNNYYQYYRRRRRRRRRRRRRRRRRRRYYWWYYYYZZZZZZZZEEEEEEEEJJJJJJJJJJXXXDDDRRDDDDDDGGGGGGGGGAAAAAAAAADDDDPWVPPPPVVYVVJJJJJJJJJJJ",
    "VVUUUUUUUVVCCCVVVVNNNNYYYYYYRRRRRRRRRRRRRRRRRRRYWWWYYYYZZZZZZZYEEEEEEEEEKJJJJJJYJJXRRRRRDDDDDDDGGWWWGTIIAAAAAAAAADDPPPPPPPPPPVPRJJJJJJJJJJJJ",
    "VVUUUUUUUUVVVVVVVVVVYNYYYYYYRRRRRRRRRRRRRRRORZZYWWWYYYYYZZZZZZZLZZZEEEEEKKKJJJYYYYYYYRRDDDDDDDDWWWWGGTIAAAAAAAAADDDPPPPPPPPPPPPJJYJJJJJJJJJJ",
    "VVVVUUUUUVVVVVVVVVVYYYYYYYYYYRRMRRRRMMMRRRROOWZZWWWYYYYYZZZZZZZZZSSEEEEEEKKGGJYYYYYYYRBBDDDDWWWWWWWWTTIITAAAALAKDDDDPPPPPPPPPPPJJJJJJJJJJJJJ",
    "VVVVVVUUUUVVVVVVVVVDYYYYYYYYYRMMMMRRMMRRRFWWWWWWWWWWWYYZZZZZZZZSSSSSEEKEEKKGGYYYYYYYJBBJDDDDWWWWWWWWTTTTTAAAALADDDDDPPPPPPPPPPPPPJJJJJJJJJJJ",
    "VVVVUUUUUVVVVVVVVVVVYYYYYYYYYMMMMRRMMMMRRWWWWWWWWWWWWYWGZZZZZZQSSSSSSSKKKKKGGGYYYYYYJJJJEDDDDWWWWWWWTTTTLAALLLLXXXXXXXKXPPPPPPPPPJJJJJJJJJJJ",
    "VVVNNNUNVVVVVVVVVVBBYYYYYYYYMMMMMMMMMMHHYWWWWWWWWWWWWWWWWWZZZZZSSSSSSSKKKKKKGGYYYYYYJJJJEDDDDWWWWWWWWLLLLLLLLLLXXXXXXXXXPPPPPPPPPFJJJJJJJJJJ",
    "VVVNNNNNVVVVDUCVVVBBYYYYYYYOOMMMMMHMMMHHHHWWWWWWWWWWWWWCCZZZZZSSSSSSSKKKKKKKKKKKKYYYJJJJEEXXDWWWWWWLLLLLLLLLLXXXXXXXXXXXXXPPPPPPPFFFFJJFFFJJ",
    "VVVVVNNNNVVJUUUUULUUYKYYYYOOOMMMHMHMMMHHHHWWWWWWZWWWWWWCCCCZZSSSSSSSZSYKKKKKKKKYYYYJJJJJJXXXXXXWWWWLLLLLLLLLLXXXXXXXXXXXZZZZPPPPFFFFFJFFFFJJ",
    "RRRNNNNNNJJJUUUUUUUUUOOOYYOOOOMMHHHMMMHHHHHAWWWWZZZWWWCCCCVSSSSSSSSSSSSCKKKKKKKYYJYJJJJJXXXXXHHXXWWLLLLLLLLLLXXXXXXXXXXZZZZZZZZZZFFFFFFFFFJJ",
    "RRRNNNNNNJJJUUUUUUUUUUOOOOOOOMMMHHHHHMMHHHAAAWWZZZZZWWCCCCVVSSSSSSSSSSSCCCKKKYYYYJJJJJJJJXXXXXXXZZZZLLLLLLLLLXXXXXXXXXXZZZZZZZZZZFFFFFFFFFFF",
    "RRNNNNNNNNNUUUUUUUUUUUOOOOOOYHMHHHHHHHMMMMOAUWWWUUUUUUUUUURVSSSSSSSSSSCCCCCQYYYYYJJJJJJJJXXXXXXXXZZLLLLLLLLLLLXXXXXXXXXZZZZZZZZFFFFFFFFFFFFF",
    "RRNNNNNNNNUUUUUUUUXXUOOOOOOOHHHHHHHHHHHHMOOAUUUUUUUUUUUUUUVVVSSSSSSSSCCCCCQQYYYYJJJJJJJJJXXXXXXXZZZZZYHLLLLLLLLXXXXXBBBBBBZZZZFFFFFFFFFFFFFF",
    "NNNNNNNNNUUQUUUUUUXOUOOOOOOHHHHHHHHHHHHHOOOOOOUUUUUUUUUUVVVVVVSSSSSSSCCQQQQQQQJJJJJJJJJXJXXXXXXZZYZYYYYJJJJLLLLLXXXXXBBBBBBZBBFFFFFFFFFFFFFF",
    "NNNNNNNNNUUUUBBBUUUOOOOOOOOOHHHHHHHHHHOOOOOOOOUUUUUUUUUUVVVVVVVVVCSSCCQQQQQQQQQJJJJJJXXXXXXXXXXYYYYYYYYJJJJLLLLLLLXBBBBBBBBBBBFFFFFFFFFFFFFF",
    "WNNNNNNNNNUBBBBBUUYOOOOOOHHHHHHHHHHHOZOOOOOOOOUUUUUUUUUUVVVVVVVCCCOSCQQQQQQQQFFVVJJJJXXXXXXXXXXYYYYYYYJJJJJJLLLLJXXXXXBBBBBBBBBFFFFFFFFFFFFF",
    "WNNNNNNBNBBBBBBBUUOOOOOOOOHHHHHHHHHHOOOOOOOOOOUUUUUUVVVVVVVVQVVCCCSSQQQQQQQQFFFVVJJJJNNNXXXXXXXYYYYYYYYJJJRJJXLLLXXXXXBBBBBBBBFFFFQQQFFFFFFF",
    "WWNNNNBBBBBBBBBBBBBBOPOOOOOHHHHHHHHHHOOOOOOOOOUUUUUUUVVVVVVVQQQQCCSSXQQQQQQMFFFFFJBNNNNNXXXXXXYYYYYYYXXXJJJJXXLLXXXXXXXIBBBBBBFFFFQQQFFFFFFF",
    "TTNNWWWBBBBBBBBBBBBBBBQOOHHHHKHHHHHHHZOOOOOOOOOOUUUUUVVVVVQQQQQQQQQQQQQQQQQFFFFFBBBNONNNXXXXXYYYYYYYYNNXXXXXXXXXXXXXXXIIBIIIIBBFFFQQQFFFFFFF",
    "TTTTTWWBBBBBBBBBBBBBBKQOOHHHHHHHHHHHZZOOOOOOOOOOUUUUUVVVVQQQQQQQQQNQQQQQQQFFFFFFBBBOONNNXXXXXXXYYYYYNNNNXNNNNNXXXXXGXXIIIIIIIBBFFFQQQFMMFFFF",
    "TTTTTWWBBCBCBBBBBBBBBQQQHHOOHHHHHHHHZZZOZOOOOOOOUUUUVVVVVVQQQQQQQQQQQQQQFFFFFFFFFBBOOOONXAXAXXYYYYYYYYNNNNNNNNNXXXXGGGBIIIIIIIBFFFQQQMMFFFQF",
    "TTTTTTWWWCCCBBBCCBQBQQQQQQOHTHHHHHHHZZZZZOOOOOOOUUVVVVVVVVQQQQQQQQQQQQQFFFFFFFFFBBBOOOOOAAAAYYYYYYYYYNNNNNNNNNNXXXBGBBBBIIIIIIBFQQQQQQQQFQQQ",
    "TTTTTTTWCCCCBCCCCQQBUQQQQQOHHHHHHHHHZZZZZZZZOOOOUVVVVVVVVQQQQQQQQQQNNQQZZZFFFFFFOOOOOOOWWWWAWYYYYYYYYYNNNNNNNNXXXBBBBIIBXIIIIIIZQQQQQQQQFQPP",
    "TTTTTTJCCCCCCCCCCQQQQQQQQQQPHHHHHZZZZZZZZZZZZOSVVVVVVVVVVQQQQQQQQQQQNQQZZZZZZFFFOOOOOWWWWWWWWYLLYYYYYKNNNNSNNNXXXXXBBBIIIIQQQQQQQQQQQQQQMQQP",
    "TTTTTTTCCYYYYYYCQQQQQQQQQQQPZHHZZZZZZZZZZZPZZOPVVVVVVVVVVVQQQQQQQQQQQQQZZZZZZFFFOOOOOWWWWWWWIHLYYKKYKKKNNNWWNNNNXXXXBBDIZZQQQQQQQQQQQQQQQQQQ",
    "TTTTTTTCCYYYYYYCQQQQQQQQQQKZZZZZZZZZZZZZZPPPPPPPPVVVVVVVVVQQQQQQQQQQQZZZZZZZZZFWOWOWWWWWWWWWWHHJHKKKKKKKNNWWNXXXXXXXBZDIZZQQQQQQQQQQQQQQQQQQ",
    "TTTTTTXXYYYYYYYCCQQQQQQQKQZZZZZZZZZZZZZPPPPPPPPPVVVVVVVVVQQQQQQQQQQQZZZZZZZZZZFWWWOWWWWWWWWWWHHHHHHHHHHWWWWYNXXXXXXXXZZZZZXZZZZQQQQQQQQQQQQG",
    "TTTTTXXXYYYYYYYCCQQQQQQQKZZZZZZZZZZZZZZPPPPPPPPPPPVVVVVVVQVQAQQQBQQQZZZZZZZZZZZWWWWWWWWWWWWWLHHHHHHHHWWWWWWWWWXWXXXXXXXZXXXXZZZQQQQQQQQQQQGG",
    "THTTXXXXYYYYYYYCQQQQQQQQWWZDZZZZZZZZZZZZPPPPPPPPPPPVVVVVVVVVQQQQQQQZZZZZZZZZZZWWWNWWWWWWWWWHHHHHHHHHHHHWWWWWWWWWXXXXXXXXXEEXZZQQQQQQQQQQQQGG",
    "TTXXXXXXYYYYYYYQQQQQQQZQWWDDZZZZZHZZZZPZPPPPPPPPPPPVPPVVVVVQQQQQQUUZZZZZZZZNNNNNNNWWWWWWWWWHWHHHHHHHHHHWWWWWWWWWWXXXXXXXEEEZZZQQQQQQQQQQGGGG",
    "XXXXXXXXYYYYYYYTQQQQQQWWWWWDDZZZHHHZZZPPPPPPPPPPPPPPPCDVDVVQQQQQQQZZZZZZZNMNNNNNNWWWWWWWWWWWWWBHHHHHHHHWWWWWWWWWWXXXXEEEEEEEMMQQQQQQQQQQGGGG",
    "XXXXXXXXXXXXXXTTTQQTQEWWWWWWWIHIHHHHZZZPMPPQPPPPPPPPPCDVDDDQQQQBQQZZZZZZNNNNNNNNNNNNWWWWWEEWWRBHHHBBHWWWWWWWWWWWWWXXEEEEEEEEEEQQQQQGGGGGGGGG",
    "LXLLLLXXXXXXTTTTTTTTWWWWWWWWWWHHHHHHZHHQMQQQQPPPPPPPCCDDDDDOOQBBBQQZZZZZNNNNNNNNNNNNWWWWEEEEERBHBBBBBBWWWWWWWWWWWWXXXEEEEEEEEEQQQGGGGGGGGGGG",
    "LLLLLLXXXXXXTTTTTTTUWWWWWWWWHHHHHHHHHHHQQQQQQQPPPCPCCCCDDDDDDDBBBBZZZZZNNNNNNNNNNNNWWWWWEEEEEEBBBBBBBBWWWWWWWWWWWXXXXEEEEEEEEEQQQGGGGGGGGGGG",
    "LLLLLLXXXXTXUUTTUUUUWWWWWWWWHHHHHHHHHHHQQQQQQQPPPCCCCCCDDDDDDDDBBBZIZHZNNNNNNNNNNNWWWWWWEEEEEABBBBBBBBWWWWWWWWWWWWXEEEEEEEEEEEQQQGGGGGGGGGGG",
    "LLLLLLXBTTTUUUUUUUUUWWWWWWWHHHHHHHHHHHHHQQQQTTPPPCCCCCDDDDDDDDABBBBZIZZNNNNNNNNNNNWWWWWWEEEEEBBBBBBBBBBWWWBWWWWWWWWNEEEEEEEEEEQQQGGGGGGGGGGG",
    "LLLLLLLBTTTUUUUUUUUUWWWWWWWWHHHHHHHHHHHHQQQQQQPPCCCCCDDDDDDDDDDBBBBZZZZNNNNNNNNNNNWWWWWWWVEEBBBBBBBBBBBBWBBBWWWWWWWOOEEEEEEEEEELLGGGGGGGGGGG",
    "LLLLMMBBUUUUUUUUUUUWWWWWWWWWWHHHHHHHHHHHBQQQQBBBBBCCCCDDDDDDDDDDBBBZBBBNNNNNNNNNNNNOOWWVVVBBBBBBBBBBBBBBBBGOWWWWFOOOOEEEEEEEEEEEEAAGGGGGGGGG",
    "LLLMMMABUUUUUUUUUUUUWWWWWWKKWHHHHHHHHHHHBQQBBBBBCCCCCDDDDDDDDDDBBBBZBBBBBBBBNNNNNOOOOWWWVBBBBBBBBBBBBBBBIIOOOWWWOOOOOOVEEEEEEAEEAAAGGGGGGGGG",
    "LLLMMMAAAUUUUUUUUUUWWWWWWWKKWXHHHHHHHHHBBBBBBBBBCCCCCCCCDDDDDDDBBBBBBBBBBQBBOOONNOOOOWWWWBBBBBBBBBBBBBBIIIOOOWWWWOOOOOOUEEEEAAAEAAAAASSGGGAA",
    "LLMMMAAAUUUUUUUUUUUWWWWWWWKGHHHHHHCCHBBBBBBBBBBBBCCCCCDDDDDDDUDBBBBBBBBBBBBBOOOOOOOOOWUUYBYBBBBBBBBBBBBIVVVVOOOWOOOOOOOUEAAAAAAAAAAAAASSGGAA",
    "LQQQQQAAAUUUUUUUUUUUUUWWKKKKHKKHHHCCBBBBBBBBBBBBBBCCCCDDDDDDDDBBBBBBBBBBBBOOOOOOOOXXOWUUYYYBBBBBBBBBBBAVVVVVOOOOOOOOOOOOOOXXXXAXXAAAAASSSAAA",
    "QQQQAQQAAAUATTTUUUUUUUUUPKKKKKKKHHCKBBBBBBBBBBBBBBBBCCDDDOKKKDBBBBBBBBBBBOOOOOOOOXXXXGUUYYBBBBBBBBBBBAAAAVVVVVOOOOOOOOOOOXXXXXXXAAXAAAAAAAAA",
    "QQQQQQAAAAAATTTTTTTTTHXXXKKKKKKKHRKKBBBBBBBBBBBBBBBCCDDDOOKKKKBBBBBBBBBBBBBOOOXXXXXUUUUUUUBBBBBBBBZBHZAAAAAVVVOOOOOOOOOXXXXXXXXXXAXAAAAAAAAA",
    "QQQQQQAAAAATTTTTTTTTTXXKKKKKKKKKHKKKEEBBBBBBBBBBBBBBBDDDOOKKKKKBXBBBXXBBBBOOOOOXXXXXUUUUUUBBLLLBZZZPZZZAAAAVVVVOOOOOOOOOXXXXXXXXXAXXXAAAAAAA",
    "QQQQQQQAATTTTTTTTTTTTXXXKKXXXKKKKKKKEBBBBBBBBBBBBBBDDNDSDOOOOKKXXXXXXXXVBBOVVVVVVXXXXUUUUUBLLLLZZZZZZZZAAAAAVCVPOOOOOOOXXXXXXXXXXXXXXAAAAAAA",
    "QQQQQQQAAATTTTTTTTXLXXXXXKXXXKKKKKEEEFFBBBBBBBBBBBBDDDDDDOOODKKXXXXXXXXVVVVVVVVVVXXXUUUUUUUZLZZZZZZZZZZZZZAAVPPPPOOOOOGGGXXXXXXXXXXAAAAAWAAA",
    "QQQQQQQAATTTTTTTTXXXXXXXXXXXXKKKKKEEEEEEBBBDBBBBBDDDDDDDDDDDDKKXXXXXXXXVVVVVVVVVVVVXXUUUUUUZZZZZZZZZZZZZZZAAPPPPPOOOOEGGGXXXXXXXXXXXAAAAAAAA",
    "QQQQQQQQQTTTTTTXXXXXXXXXXXXXXXKKEEEEEEEEBBBDDBBMMDDDDDDDDDDDDDKKXXXXXXXVVVVVVVVVVVVXXURUUUUZZZZZZZZZZZZZZZZZPPPPOOOOEEGGGGXXXXXXXXXXAAAAAAAA",
    "QQQQQQQQQQMTTTTXXXXXXXXXXXXXXKKEEEEEEEEEEBBBBBMMMDDDDDDDDDDDDDXXGXXXXXXXVVVVVVVVVVVXXUUUUUUUXXZZZZZZZZZZZZPPPPPPPOOOEEGGGGGXXXXXAHXKAAAAAAAA",
    "QQQQQQQQQQTTTTTXXXXXXXXXXXXXXXXEEEEEEEEEEEBEEBMDMDDDDDDDDDDDDIXXXXXXXZZZVVVVVVVVVVVXXUHUUUUUXXZZZZZZZZZZIZPPPPPPYYOYEEEGGGGGGGXXAHXXAAAAAAAA",
    "QQQQQQQQQQQITTTXXXXXXXXXXXXXEEXEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDIIXXXXXXXXXVVVVVVVVVVXXXUUUUUUUUXXZZZZZZZZZZZPPPPPPYYOYEEEEGGGGGAAAAAANAAAAAAAA",
    "QQQQQQQQQIIITTTTXXXXXXXXXXXEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDDXXXXXXXXXVVVVVVVVVXXXXXXXUXUXXXZZZZZZZZZZZZPPPPPYYYYEEEGGGGGGAAAAAAAAAAAAAAA",
    "QQQQQQQQQIIIIIIIXXXXXXXXXXXXXEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDDXXXXXXXXXXVVXVXVVXXVXXXXXXXXXXXXXZZZZZZZZZZZZPPPPPPPYEEEGGGGGGGGGAAAAAAAAAAAAA",
    "QQQQQQQQIIIIIIIXXXXXXXXXXXXXXXEEEEEEEEEEEEEEEEEDDDDDDDDDDDDDDXXXXXXXXXXXXXXXXVXXXVVXXXXXXXXXXXXXZZZZZZZZZZAAPPAAAAEEEEEGGGGGGGGAAAAAAAAAAAAA",
    "QQQQQQQQIIIIIIIXXHXAXXXXXXRXXEEEEEEEEEEEEEEEEEEDCDWDEEDDDDDDDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZZZZZZZPZAAAAAAAAAAEEEGGGGGGGAAAAAAAAAAAAAAN"
);

run($data1);

?>
